### ISSUE TITLE
[其他]: 优化Github Actions

### ISSUE THREAD

**Issue by AstralFlare-owo** [zly2006/reden-is-what-we-made#22]
### 描述

可以将复杂的secret&API发布改为使用开源的Github Actions任务模板进行发布，任务格式如下：
```yaml
jobs:
    - name: Create Release
      uses: softprops/action-gh-release@v0.1.13
      with:
        name: 发布名称
        body: "你的发布描述"
        draft: 是否为草稿
        files: 编译文件地址（支持YAML多选）
        fail_on_unmatched_files: 无匹配文件时是否失败
        prerelease: 是否为预发布
```

可以参考我的储存库 TuanZiGit/BukkitBackdoor
